name: App metrics
description: Collect and test app metrics

inputs:
  config:
    description: Configuration file (YAML or HOCON)
    required: true
  sauce-user:
    description: SauceLabs username
    required: true
  sauce-key:
    description: SauceLabs access key
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        echo Using config file: ${{ inputs.config }}
        cat ${{ inputs.config }}
      shell: bash

    - run: ./gradlew --no-daemon :test
      shell: bash
      env:
        TEST_CONFIG: ${{ inputs.config }}
        SAUCE_USERNAME: ${{ inputs.sauce-user }}
        SAUCE_ACCESS_KEY: ${{ inputs.sauce-key }}

    - name: Find Comment
      uses: peter-evans/find-comment@1769778a0c5bd330272d749d12c036d65e70d39d # v2.0.0
      if: github.event.pull_request.number
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: '## Performance metrics'

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32 # v2.0.0
      if: github.event.pull_request.number
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: |
          ## Performance metrics :rocket:
          |                   |                                    Plain  |                              With Sentry  |                                        Diff  |
          |-------------------|-----------------------------------------: |-----------------------------------------: |--------------------------------------------: |
          | Startup time (ms) | ${{ steps.tests.outputs.StartTimeApp1 }}  | ${{ steps.tests.outputs.StartTimeApp2 }}  | **${{ steps.tests.outputs.StartTimeDiff }}** |
          | Size (bytes)      | ${{ steps.tests.outputs.SizeApp1 }}       | ${{ steps.tests.outputs.SizeApp2 }}       | **${{ steps.tests.outputs.SizeDiff }}**      |
