name: App metrics
description: Collect and test app metrics

inputs:
  config:
    description: Configuration file (YAML or HOCON)
    required: true
  sauce-user:
    description: SauceLabs username
    required: true
  sauce-key:
    description: SauceLabs access key
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        echo Using config file: ${{ inputs.config }}
        cat ${{ inputs.config }}
      shell: bash
    - run: ./gradlew :test
      shell: bash
      env:
        TEST_CONFIG: ${{ inputs.config }}
        SAUCE_USERNAME: ${{ inputs.sauce-user }}
        SAUCE_ACCESS_KEY: ${{ inputs.sauce-key }}
