# Test the action itself
on:
  push:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          config: tests/android.yml
          sauce-user: ${{ secrets.SAUCE_USER }}
          sauce-key: ${{ secrets.SAUCE_KEY }}

  ios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          config: tests/ios.yml
          sauce-user: ${{ secrets.SAUCE_USER }}
          sauce-key: ${{ secrets.SAUCE_KEY }}
